name: Lint

on:
  push:
    branches:
      - main
      - game_dev
    paths:
      - 'src/**'
      - 'bobcat_ui/**'
      - 'test/**'
      - 'Makefile'
      - 'dockerfile'
  pull_request:
    branches:
      - main
      - game_dev
    paths:
      - 'src/**'
      - 'bobcat_ui/**'
      - 'test/**'
      - 'Makefile'
      - 'dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Check Code Style
      run: make lint
