name: Maketest

on:
  push:
    branches:
      - main
      - game_dev
    paths:
      - 'src/**'
      - 'bobcat_ui/**'
      - 'test/**'
      - 'Makefile'
      - 'dockerfile'
  pull_request:
    branches:
      - main
      - game_dev
    paths:
      - 'src/**'
      - 'bobcat_ui/**'
      - 'test/**'
      - 'Makefile'
      - 'dockerfile'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get update
        sudo apt-get install -y libfltk1.3-dev libgl1-mesa-dev xvfb

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install fltk

    - name: Run Tests (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run make test

    - name: Run Tests (macOS)
      if: runner.os == 'macOS'
      run: make test
